{% set name = "google-cloud-texttospeech" %}
{% set version = "2.10.2" %}
{% set sha256 = "1329080f1a0ef1e3e9e212ed20d4f3fd16a17d2e0a53b1a1c12e2090c040df6c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-api-core-grpc >=1.26.0,<3.0.0dev
    - proto-plus >=1.4.0
    - packaging >=14.3

test:
  imports:
    - grpc
    - google.cloud.texttospeech_v1

about:
  home: https://github.com/googleapis/python-texttospeech
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Text-to-Speech API client library
  description: "Google Cloud Text-to-Speech API synthesizes natural-sounding speech by applying powerful neural network models.\nSee the [quick start guide](https://googleapis.dev/python/texttospeech/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/texttospeech/latest/index.html
  dev_url: https://github.com/googleapis/python-texttospeech

extra:
  recipe-maintainers:
    - parthea
